/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public final class TailRecursiveFactorial {
    public static int tailRecursiveFactorial(int n, int r) {
        if (n <= 1)
            return r;
        return tailRecursiveFactorial(n - 1, n * r);
    }
}
